---

- name: longhorn | disks | create mount directory
  file:
    path: /var/lib/longhorn
    state: directory
  when:
  - longhorn.enabled is defined
  - longhorn.enabled == true

- name: longhorn | disks | create new LVM volume group
  become: true
  lvg:
    vg: "longhorn-vg"
    pvs: "{{ longhorn.disks | join(',') }}"
    state: present
  when:
  - longhorn.enabled is defined
  - longhorn.enabled == true

- name: longhorn | disks | create new LVM logical volume
  become: true
  lvol:
    vg: "longhorn-vg"
    lv: "lv0"
    size: "100%FREE"
    shrink: false
    opts: "{{ longhorn.opts | default('') }}"
    state: present
  when:
  - longhorn.enabled is defined
  - longhorn.enabled == true

- name: longhorn | disks | create new filesystem on new LVM logical volume
  become: true
  filesystem:
    fstype: "{{ longhorn.filesystem | default('ext4') }}"
    dev: "/dev/longhorn-vg/lv0"
    resizefs: yes
  when:
  - longhorn.enabled is defined
  - longhorn.enabled == true
  
- name: longhorn | disks | mounting new filesystem
  become: true
  ansible.posix.mount:
    path: "{{ longhorn.mountpoint }}"
    src: "/dev/longhorn-vg/lv0"
    fstype: "{{ longhorn.filesystem }}"
    state: mounted
    opts: "{{ longhorn.mount_opts | default('defaults') }}"
  when:
  - longhorn.enabled is defined
  - longhorn.enabled == true
