---
- name: longhorn | meta | apply labels
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/create-default-disk=config
  # Cannot use loop w/ hostvars in when... https://github.com/ansible/ansible/issues/68364
  with_items:
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"
  register: apply_longhorn_labels
  retries: 5
  until: apply_longhorn_labels is success
  when:
  - k8s_control_node is defined
  - k8s_control_node
  - hostvars[item].longhorn.enabled is defined
  - hostvars[item].longhorn.enabled == true

- name: longhorn | meta | apply annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  command: kubectl annotate --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/default-disks-config='[{"path":"{{ hostvars[item]['longhorn']['mountpoint'] }}", "name":"longhorn", "allowScheduling":true}]'
  # Cannot use loop w/ hostvars in when... https://github.com/ansible/ansible/issues/68364
  with_items:
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"
  register: apply_longhorn_annotations
  retries: 5
  until: apply_longhorn_annotations is success
  when: 
  - k8s_control_node is defined
  - k8s_control_node
  - hostvars[item].longhorn.enabled is defined
  - hostvars[item].longhorn.enabled == true

- name: longhorn | meta | remove labels
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/create-default-disk-
  # Cannot use loop w/ hostvars in when... https://github.com/ansible/ansible/issues/68364
  with_items:
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"
  register: remove_longhorn_labels
  retries: 5
  until: remove_longhorn_labels is success
  when: 
  - k8s_control_node is defined
  - k8s_control_node
  - (hostvars[item].longhorn.enabled is not defined or not hostvars[item].longhorn.enabled)

- name: longhorn | meta | remove annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  command: kubectl annotate --overwrite node {{ hostvars[item]['ansible_hostname'] }} node.longhorn.io/default-disks-config-
  # Cannot use loop w/ hostvars in when... https://github.com/ansible/ansible/issues/68364
  with_items:
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"
  register: remove_longhorn_annotations
  retries: 5
  until: remove_longhorn_annotations is success
  when:
  - k8s_control_node is defined
  - k8s_control_node
  - (hostvars[item].longhorn.enabled is not defined or not hostvars[item].longhorn.enabled)
