---

all:
  children:
    # Master group, do not change the 'master' name
    # hosts should match the filenames in 'host_vars'
    master:
      hosts:
        franxx.56k.jp:
    # Worker group, do not change the 'worker' name
    # hosts should match the filenames in 'host_vars'
    worker:
      hosts:
        darling.56k.jp:
        elias.56k.jp:

    # Kubespray group mappings
    kube-master:
      children:
        master:
    kube-node:
      children:
        master:
        worker:
    etcd:
      children:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
    kubespray:
      children:
        master:
        worker:
