---

- name: keepalived | install package
  become: true
  apt:
    name: keepalived
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
  register: apt_install_keepalived
  retries: 5
  until: apt_install_keepalived is success
  when:
  - k3s_control_node is defined
  - k3s_control_node 
  - keepalived.enabled is defined
  - keepalived.enabled

- name: keepalived | copy configuration
  become: true
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  when:
  - k3s_control_node is defined
  - k3s_control_node 
  - keepalived.enabled is defined
  - keepalived.enabled
