---

- name: motd | news module exists
  stat:
    path: /etc/default/motd-news
  register: motd_news

- name: motd | disable news
  lineinfile:
    dest: /etc/default/motd-news
    state: present
    regexp: '^ENABLED='
    line: 'ENABLED=0'
  when: motd_news.stat.exists
