---

# IP address of node
ansible_host: "172.16.20.11"
ip: "172.16.20.11"

# Format and mount a device for longhorn
longhorn:
  enabled: true
  disks:
  - "/dev/sdb"
  filesystem: "ext4"
  mountpoint: "/var/lib/longhorn"
  # Defines additional lvcreate options (e.g. stripes, stripesize, etc)
  # lvcreate_opts: ""
  # Defines additional mount options (e.g. noatime, noexec, etc)
  # mount_opts: ""
